const express = require('express');
const cors = require('cors');
const fs = require('fs');
const path = require('path');
const http = require('http');
const https = require('https');
const jwt = require('jsonwebtoken');

const app = express();
const CONFIG_PATH = path.join(process.env.HOME, '.codex-gateway', 'config.json');
const JWT_SECRET = path.join(process.env.HOME, '.codex-gateway', '.jwt-secret');
const PROXY_PORT = 11434;
const API_PORT = 3000;

// JWT secret
function getJwtSecret() {
  try {
    return fs.readFileSync(JWT_SECRET, 'utf8').trim();
  } catch {
    const secret = require('crypto').randomBytes(32).toString('hex');
    fs.writeFileSync(JWT_SECRET, secret);
    return secret;
  }
}

// Ensure config directory exists
fs.mkdirSync(path.dirname(CONFIG_PATH), { recursive: true });

// Default config
function loadConfig() {
  try {
    return JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));
  } catch {
    return { activeProvider: null, providers: {} };
  }
}

function saveConfig(config) {
  fs.writeFileSync(CONFIG_PATH, JSON.stringify(config, null, 2));
  generateBashAliases(config);
}

function generateBashAliases(config) {
  const aliasesDir = path.join(process.env.HOME, '.codex-gateway');

  // Generate Codex aliases
  let codexLines = ['# Auto-generated by Codex Gateway - Do not edit manually', ''];
  for (const [id, p] of Object.entries(config.providers)) {
    if (!p.baseUrl) continue;
    const isActive = config.activeProvider === id;
    codexLines.push(`# ${p.name}${isActive ? ' (active)' : ''}`);
    codexLines.push(`codex-${id}() {`);
    codexLines.push('  if ! curl -s http://localhost:11434/v1/models >/dev/null 2>&1; then');
    codexLines.push('    cd ~/codex-gateway && nohup node server.js > /tmp/codex-gateway.log 2>&1 &');
    codexLines.push('    sleep 2');
    codexLines.push('  fi');
    codexLines.push(`  curl -s -X POST http://localhost:3000/api/providers/${id}/activate > /dev/null`);
    codexLines.push('  local model=$(curl -s http://localhost:11434/v1/models | python3 -c "import sys,json; print(json.load(sys.stdin)[\'data\'][0][\'id\'])" 2>/dev/null)');
    codexLines.push('  export OPENAI_API_KEY="any-key"');
    codexLines.push('  export CODEX_OSS_BASE_URL="http://localhost:11434/v1"');
    codexLines.push('  codex --oss --local-provider ollama -m "$model" "$@"');
    codexLines.push('}');
    codexLines.push('');
  }
  codexLines.push('# Default (active provider)');
  codexLines.push('codexgo() {');
  codexLines.push('  if ! curl -s http://localhost:11434/v1/models >/dev/null 2>&1; then');
  codexLines.push('    cd ~/codex-gateway && nohup node server.js > /tmp/codex-gateway.log 2>&1 &');
  codexLines.push('    sleep 2');
  codexLines.push('  fi');
  codexLines.push('  local model=$(curl -s http://localhost:11434/v1/models | python3 -c "import sys,json; print(json.load(sys.stdin)[\'data\'][0][\'id\'])" 2>/dev/null)');
  codexLines.push('  export OPENAI_API_KEY="any-key"');
  codexLines.push('  export CODEX_OSS_BASE_URL="http://localhost:11434/v1"');
  codexLines.push('  codex --oss --local-provider ollama -m "$model" "$@"');
  codexLines.push('}');
  fs.writeFileSync(path.join(aliasesDir, 'codex-aliases.sh'), codexLines.join('\n') + '\n');

  // Generate Claude aliases
  let claudeLines = ['# Auto-generated by Codex Gateway - Do not edit manually', ''];
  for (const [id, p] of Object.entries(config.providers)) {
    if (!p.anthropicUrl || !p.claudeModel) continue;
    const isActive = config.activeProvider === id;
    claudeLines.push(`# ${p.name}${isActive ? ' (active)' : ''}`);
    claudeLines.push(`claude-${id}() {`);
    claudeLines.push('  unset ANTHROPIC_API_KEY');
    claudeLines.push('  unset ANTHROPIC_AUTH_TOKEN');
    claudeLines.push(`  export ANTHROPIC_BASE_URL="${p.anthropicUrl}"`);
    claudeLines.push(`  export ANTHROPIC_AUTH_TOKEN="${p.apiKey}"`);
    claudeLines.push(`  export ANTHROPIC_MODEL="${p.claudeModel}"`);
    claudeLines.push(`  export ANTHROPIC_DEFAULT_OPUS_MODEL="${p.claudeModel}"`);
    claudeLines.push(`  export ANTHROPIC_DEFAULT_SONNET_MODEL="${p.claudeModel}"`);
    claudeLines.push(`  export ANTHROPIC_DEFAULT_HAIKU_MODEL="${p.claudeModel}"`);
    claudeLines.push('  export CLAUDE_CODE_EFFORT_LEVEL="max"');
    claudeLines.push('  claude --dangerously-skip-permissions "$@"');
    claudeLines.push('}');
    claudeLines.push('');
  }
  claudeLines.push('# Default (active provider)');
  claudeLines.push('claudego() {');
  claudeLines.push('  local provider_id=$(curl -s http://localhost:3000/api/status | python3 -c "import sys,json; print(json.load(sys.stdin).get(\'activeClaude\',\'\') or json.load(sys.stdin).get(\'activeProvider\',\'\'))" 2>/dev/null)');
  claudeLines.push('  if [ -n "$provider_id" ]; then');
  claudeLines.push('    "claude-$provider_id" "$@"');
  claudeLines.push('  else');
  claudeLines.push('    echo "No active provider configured"');
  claudeLines.push('  fi');
  claudeLines.push('}');
  fs.writeFileSync(path.join(aliasesDir, 'claude-aliases.sh'), claudeLines.join('\n') + '\n');

  console.log('Generated aliases: codex-aliases.sh, claude-aliases.sh');
}

// Initialize config with Xiaomi if not exists
if (!fs.existsSync(CONFIG_PATH)) {
  saveConfig({
    password: 'codex2026',
    activeProvider: 'xiaomi',
    providers: {
      xiaomi: {
        name: '小米 MiMo',
        baseUrl: 'https://token-plan-cn.xiaomimimo.com/v1',
        apiKey: 'tp-clknkhid34gyle3254pbuq2va55gpvgjukv2g107o2wrgnxq',
        models: ['mimo-v2.5-pro', 'mimo-v2.5', 'mimo-v2-pro'],
        anthropicUrl: 'https://token-plan-cn.xiaomimimo.com/anthropic',
        claudeModel: 'mimo-v2.5-pro[1m]'
      }
    }
  });
}

// Auth middleware
function authMiddleware(req, res, next) {
  const token = req.headers.authorization?.replace('Bearer ', '');
  if (!token) return res.status(401).json({ error: 'Unauthorized' });
  try {
    jwt.verify(token, getJwtSecret());
    next();
  } catch {
    res.status(401).json({ error: 'Invalid token' });
  }
}

// API routes
app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, 'frontend', 'dist')));

// Login endpoint
app.post('/api/login', (req, res) => {
  const config = loadConfig();
  const { password } = req.body;
  if (password === config.password) {
    const token = jwt.sign({ role: 'admin' }, getJwtSecret(), { expiresIn: '7d' });
    res.json({ success: true, token });
  } else {
    res.status(401).json({ error: 'Wrong password' });
  }
});

// Change password
app.post('/api/password', authMiddleware, (req, res) => {
  const config = loadConfig();
  const { oldPassword, newPassword } = req.body;
  if (oldPassword !== config.password) return res.status(400).json({ error: 'Wrong old password' });
  config.password = newPassword;
  saveConfig(config);
  res.json({ success: true });
});

// Get all providers (public for status check)
app.get('/api/providers', authMiddleware, (req, res) => {
  const config = loadConfig();
  res.json(config);
});

// Add provider
app.post('/api/providers', authMiddleware, (req, res) => {
  const config = loadConfig();
  const { id, name, baseUrl, apiKey, models, anthropicUrl, claudeModel } = req.body;
  config.providers[id] = { name, baseUrl, apiKey, models, anthropicUrl, claudeModel };
  saveConfig(config);
  res.json({ success: true });
});

// Update provider
app.put('/api/providers/:id', authMiddleware, (req, res) => {
  const config = loadConfig();
  const { name, baseUrl, apiKey, models, anthropicUrl, claudeModel } = req.body;
  if (config.providers[req.params.id]) {
    config.providers[req.params.id] = { name, baseUrl, apiKey, models, anthropicUrl, claudeModel };
    saveConfig(config);
    res.json({ success: true });
  } else {
    res.status(404).json({ error: 'Provider not found' });
  }
});

// Delete provider
app.delete('/api/providers/:id', authMiddleware, (req, res) => {
  const config = loadConfig();
  const { type } = req.query; // 'codex' or 'claude'
  const p = config.providers[req.params.id];
  if (!p) return res.status(404).json({ error: 'Provider not found' });

  if (type === 'codex') {
    // Only remove Codex config
    delete p.baseUrl;
    delete p.models;
    if (config.activeCodex === req.params.id) config.activeCodex = null;
  } else if (type === 'claude') {
    // Only remove Claude config
    delete p.anthropicUrl;
    delete p.claudeModel;
    if (config.activeClaude === req.params.id) config.activeClaude = null;
  }

  // If both configs are gone, remove the provider entirely
  if (!p.baseUrl && !p.anthropicUrl) {
    delete config.providers[req.params.id];
    if (config.activeProvider === req.params.id) config.activeProvider = null;
  }

  saveConfig(config);
  res.json({ success: true });
});

// Activate provider
app.post('/api/providers/:id/activate', authMiddleware, (req, res) => {
  const config = loadConfig();
  const { type } = req.body; // 'codex' or 'claude'
  if (config.providers[req.params.id]) {
    if (type === 'claude') {
      config.activeClaude = req.params.id;
    } else {
      config.activeCodex = req.params.id;
    }
    // Keep legacy activeProvider for proxy compatibility
    config.activeProvider = req.params.id;
    saveConfig(config);
    res.json({ success: true });
  } else {
    res.status(404).json({ error: 'Provider not found' });
  }
});

// Status
app.get('/api/status', (req, res) => {
  const config = loadConfig();
  res.json({
    proxyPort: PROXY_PORT,
    activeProvider: config.activeProvider,
    activeCodex: config.activeCodex || config.activeProvider,
    activeClaude: config.activeClaude || config.activeProvider,
    activeConfig: config.activeProvider ? config.providers[config.activeProvider] : null
  });
});

// Usage statistics
const USAGE_PATH = path.join(process.env.HOME, '.codex-gateway', 'usage.json');

function loadUsage() {
  try {
    return JSON.parse(fs.readFileSync(USAGE_PATH, 'utf8'));
  } catch {
    return { providers: {}, daily: [], total: { requests: 0, promptTokens: 0, completionTokens: 0, totalTokens: 0 } };
  }
}

function saveUsage(usage) {
  fs.writeFileSync(USAGE_PATH, JSON.stringify(usage, null, 2));
}

function trackUsage(providerId, model, usage) {
  const data = loadUsage();
  const today = new Date().toISOString().slice(0, 10);

  // Provider stats
  if (!data.providers[providerId]) {
    data.providers[providerId] = { models: {}, total: { requests: 0, promptTokens: 0, completionTokens: 0, totalTokens: 0 } };
  }
  const prov = data.providers[providerId];
  if (!prov.models[model]) {
    prov.models[model] = { requests: 0, promptTokens: 0, completionTokens: 0, totalTokens: 0 };
  }
  prov.models[model].requests++;
  prov.models[model].promptTokens += usage.prompt_tokens || 0;
  prov.models[model].completionTokens += usage.completion_tokens || 0;
  prov.models[model].totalTokens += usage.total_tokens || 0;
  prov.total.requests++;
  prov.total.promptTokens += usage.prompt_tokens || 0;
  prov.total.completionTokens += usage.completion_tokens || 0;
  prov.total.totalTokens += usage.total_tokens || 0;

  // Daily stats
  if (!data.daily) data.daily = [];
  let dayEntry = data.daily.find(d => d.date === today);
  if (!dayEntry) {
    dayEntry = { date: today, requests: 0, promptTokens: 0, completionTokens: 0, totalTokens: 0, providers: {} };
    data.daily.push(dayEntry);
  }
  dayEntry.requests++;
  dayEntry.promptTokens += usage.prompt_tokens || 0;
  dayEntry.completionTokens += usage.completion_tokens || 0;
  dayEntry.totalTokens += usage.total_tokens || 0;
  if (!dayEntry.providers[providerId]) {
    dayEntry.providers[providerId] = { requests: 0, promptTokens: 0, completionTokens: 0, totalTokens: 0 };
  }
  dayEntry.providers[providerId].requests++;
  dayEntry.providers[providerId].promptTokens += usage.prompt_tokens || 0;
  dayEntry.providers[providerId].completionTokens += usage.completion_tokens || 0;
  dayEntry.providers[providerId].totalTokens += usage.total_tokens || 0;

  // Keep last 90 days
  if (data.daily.length > 90) data.daily = data.daily.slice(-90);

  // Total
  data.total.requests++;
  data.total.promptTokens += usage.prompt_tokens || 0;
  data.total.completionTokens += usage.completion_tokens || 0;
  data.total.totalTokens += usage.total_tokens || 0;

  saveUsage(data);
}

app.get('/api/usage', authMiddleware, (req, res) => {
  res.json(loadUsage());
});

app.delete('/api/usage', authMiddleware, (req, res) => {
  saveUsage({ providers: {}, total: { requests: 0, promptTokens: 0, completionTokens: 0, totalTokens: 0 } });
  res.json({ success: true });
});

// Serve frontend
app.get('/{*path}', (req, res) => {
  res.sendFile(path.join(__dirname, 'frontend', 'dist', 'index.html'));
});

// Proxy server (Ollama compatible)
function createProxyServer() {
  const proxyApp = express();
  proxyApp.use(express.json({ limit: '10mb' }));

  // Handle pull requests (fake success)
  proxyApp.post('/api/pull', (req, res) => {
    res.setHeader('Content-Type', 'application/x-ndjson');
    res.write(JSON.stringify({ status: 'success' }) + '\n');
    res.write(JSON.stringify({ status: 'complete' }) + '\n');
    res.end();
  });

  // Handle version
  proxyApp.get('/api/version', (req, res) => {
    res.json({ version: '0.135.0' });
  });

  // Handle tags
  proxyApp.get('/api/tags', (req, res) => {
    const config = loadConfig();
    const provider = config.activeProvider ? config.providers[config.activeProvider] : null;
    if (!provider) return res.json({ models: [] });
    res.json({
      models: provider.models.map(m => ({
        name: m,
        model: m,
        modified_at: new Date().toISOString()
      }))
    });
  });

  // Handle models
  proxyApp.get('/v1/models', (req, res) => {
    const config = loadConfig();
    const provider = config.activeProvider ? config.providers[config.activeProvider] : null;
    if (!provider) return res.json({ object: 'list', data: [] });
    res.json({
      object: 'list',
      data: provider.models.map(m => ({
        id: m,
        object: 'model',
        owned_by: config.activeProvider
      }))
    });
  });

  // Handle responses endpoint
  proxyApp.all('/v1/responses', (req, res) => {
    const config = loadConfig();
    const provider = config.activeProvider ? config.providers[config.activeProvider] : null;
    if (!provider) {
      return res.status(502).json({ error: 'No active provider configured' });
    }

    const data = req.body;
    const isStream = data.stream || false;

    // Convert input to messages
    const messages = [];
    if (data.instructions) {
      messages.push({ role: 'system', content: data.instructions });
    }
    for (const item of (data.input || [])) {
      if (typeof item === 'string') {
        messages.push({ role: 'user', content: item });
      } else if (item.role === 'user' || item.role === 'assistant' || item.role === 'developer') {
        let content = item.content || '';
        if (Array.isArray(content)) {
          content = content.map(p => {
            if (p.type === 'input_text') return p.text;
            if (typeof p === 'string') return p;
            return '';
          }).join(' ');
        }
        const role = item.role === 'developer' ? 'system' : item.role;
        messages.push({ role, content });
      }
    }

    // Build chat completions request
    const chatData = {
      model: data.model || provider.models[0],
      messages,
      stream: isStream
    };

    const url = new URL(provider.baseUrl + '/chat/completions');
    const options = {
      hostname: url.hostname,
      port: url.port || 443,
      path: url.pathname,
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${provider.apiKey}`
      }
    };

    const proto = url.protocol === 'https:' ? https : http;
    const proxyReq = proto.request(options, (proxyRes) => {
      if (isStream) {
        res.setHeader('Content-Type', 'text/event-stream');
        res.setHeader('Cache-Control', 'no-cache');
        res.setHeader('Connection', 'keep-alive');

        const responseId = `resp_${Date.now()}`;

        // Send response.created
        res.write(`data: ${JSON.stringify({
          type: 'response.created',
          response: {
            id: responseId,
            object: 'response',
            created_at: Math.floor(Date.now() / 1000),
            model: data.model || provider.models[0],
            output: [],
            status: 'in_progress'
          }
        })}\n\n`);

        // Send output_item.added
        res.write(`data: ${JSON.stringify({
          type: 'response.output_item.added',
          output_index: 0,
          item: {
            id: `${responseId}_item_0`,
            type: 'message',
            role: 'assistant',
            content: []
          }
        })}\n\n`);

        let fullText = '';
        let buffer = '';

        proxyRes.on('data', (chunk) => {
          buffer += chunk.toString();
          const lines = buffer.split('\n');
          buffer = lines.pop() || '';

          for (const line of lines) {
            const trimmed = line.trim();
            if (!trimmed || !trimmed.startsWith('data: ')) continue;
            const jsonStr = trimmed.slice(6);
            if (jsonStr === '[DONE]') continue;

            try {
              const chunk = JSON.parse(jsonStr);
              const delta = chunk.choices?.[0]?.delta || {};
              const content = delta.content || '';
              const reasoning = delta.reasoning_content || '';

              if (reasoning) {
                res.write(`data: ${JSON.stringify({
                  type: 'response.reasoning_text.delta',
                  output_index: 0,
                  delta: reasoning
                })}\n\n`);
              }

              if (content) {
                fullText += content;
                res.write(`data: ${JSON.stringify({
                  type: 'response.output_text.delta',
                  output_index: 0,
                  content_index: 0,
                  delta: content
                })}\n\n`);
              }
            } catch (e) {}
          }
        });

        proxyRes.on('end', () => {
          // Send output_text.done
          res.write(`data: ${JSON.stringify({
            type: 'response.output_text.done',
            output_index: 0,
            content_index: 0,
            text: fullText
          })}\n\n`);

          // Send output_item.done
          res.write(`data: ${JSON.stringify({
            type: 'response.output_item.done',
            output_index: 0,
            item: {
              id: `${responseId}_item_0`,
              type: 'message',
              role: 'assistant',
              content: [{ type: 'output_text', text: fullText }]
            }
          })}\n\n`);

          // Send response.completed
          res.write(`data: ${JSON.stringify({
            type: 'response.completed',
            response: {
              id: responseId,
              object: 'response',
              created_at: Math.floor(Date.now() / 1000),
              model: data.model || provider.models[0],
              output: [{
                id: `${responseId}_item_0`,
                type: 'message',
                role: 'assistant',
                content: [{ type: 'output_text', text: fullText }]
              }],
              status: 'completed'
            }
          })}\n\n`);

          res.write('data: [DONE]\n\n');
          res.end();

          // Track usage for streaming (estimate from text length)
          const model = data.model || provider.models[0];
          const estTokens = Math.ceil(fullText.length / 3);
          trackUsage(config.activeProvider, model, { prompt_tokens: 0, completion_tokens: estTokens, total_tokens: estTokens });
        });
      } else {
        // Non-streaming
        let body = '';
        proxyRes.on('data', chunk => body += chunk);
        proxyRes.on('end', () => {
          try {
            const respData = JSON.parse(body);

            // Track usage
            if (respData.usage) {
              trackUsage(config.activeProvider, respData.model || data.model || provider.models[0], respData.usage);
            }

            const response = {
              id: respData.id || '',
              object: 'response',
              created: respData.created || 0,
              model: respData.model || '',
              output: [{
                type: 'message',
                role: 'assistant',
                content: [{
                  type: 'output_text',
                  text: respData.choices?.[0]?.message?.content || ''
                }]
              }]
            };
            res.json(response);
          } catch (e) {
            res.status(502).json({ error: 'Invalid response from provider' });
          }
        });
      }
    });

    proxyReq.on('error', (e) => {
      res.status(502).json({ error: `Proxy error: ${e.message}` });
    });

    proxyReq.write(JSON.stringify(chatData));
    proxyReq.end();
  });

  return proxyApp;
}

// Start servers
const proxyServer = createProxyServer();

proxyServer.listen(PROXY_PORT, '127.0.0.1', () => {
  console.log(`Proxy server running on http://localhost:${PROXY_PORT}`);
});

app.listen(API_PORT, '0.0.0.0', () => {
  console.log(`API server running on http://localhost:${API_PORT}`);
  console.log(`Web UI: http://localhost:${API_PORT}`);
});
